model: 
  model_id: "llava-hf/llava-v1.6-mistral-7b-hf"
  device: "auto"
  dtype: "float16"
  low_cpu_mem: true
  quantize: 
    enabled: true
    quant_type: "8bit"

generation: 
  max_new_tokens: 100
  min_new_tokens: 20
  num_beams: 5
  do_sample: true
  temperature: 0.7
  top_k: 50
  top_p: 0.9
  repetition_penalty: 1.2
  length_penalty: 1.2
  no_repeat_ngram_size: 3
  early_stopping: true
  return_dict_in_generate: false
  output_scores: false

processor: 
  model_id: "llava-hf/llava-v1.6-mistral-7b-hf"
  device: "auto"
  return_tensors: "pt"
  padding: "max_length"
  default_prompt: "Create a positive prompt for the image."
  img_h: 224
  img_w: 224
  batch_size: 4
