model: 
  model_id: "nlpconnect/vit-gpt2-image-captioning",
  device: "cuda", 
  dtype: "float16", 
  low_cpu_mem: true

generation: 
  max_new_tokens: 100, 
  num_beams: 5,
  do_sample: true, 
  temperature: 0.7,
  top_p: 0.9,
  repetition_penalty: 1.2,

processor: 

batch_size: 4
